<?php

function favorites_menu()
{
	$items = array();
	$items['movie'] = array(
		'title' => "My Favorite Movies",
		'page callback' => 'favorite_movies',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		);

	$items['books'] = array(
		'title' => "My Favorite Books",
		'page callback' => 'favorite_books',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		);
	$items['songs'] = array(
		'title' => "My Favorite Songs",
		'page callback' => 'favorite_songs',
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
		); 
	return $items;
}

function favorite_movies()
{
	return '
	<ul>
		<li>Eternal Sunshine</li>
	</ul>
	';
}

function favorite_books()
{
	return '
	<ul>
		<li>JungleLand</li>
	</ul>
	';
}

function favorite_songs()
{
	return '
	<ul>
		<li>This is the Place</li>
	</ul>
	';
}



//


