<?php

function shift_cipher_menu() {
  $items = array();
  $items['shift_cipher'] = array(
    'title' => 'Shift Cipher!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
	);

  $items['shift_cipher_success_page'] = array(
    'title' => 'Success!',
    'page callback' => 'shift_cipher_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function shift_cipher_form() {
  $form['shift_value'] = array(
    '#title' => 'Shift Value',
    '#type' => 'textfield',
    '#description' => t('Enter value to be shifted'),
    '#element_validate' => array('element_validate_number', 'element_validate_positive'),
  );
  $form['direction'] = array(
    '#title' => 'Direction',
    '#type' => 'textfield',
    '#description' => t('Enter "left" or "right"'),
    '#element_validate' => array('element_validate_direction'),
  );
  $form['phrase'] = array(
    '#title' => 'Phrase',
    '#type' => 'textfield',
    '#description' => t('Enter Phrase to be shifted'),
    //'#element_validate' => array(''),
  );

   $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Go',
  );

  return $form;
}

function element_validate_positive($element) {
	$user_number = $element['#value'];
	if($user_number < 1) {
		form_error($element, t('you must enter a number greater than zero'));
	}
}

function element_validate_direction($element) {
	
	$directions = array('right', 'left');
	$user_direction = strtolower($element['#value']);

	if(!in_array($user_direction, $directions)) {
		form_error($element, t('you must enter "right" or "left"'));
	}
}

function shift_cipher_form_submit($form, &$form_state) {

	$shift_value = $form_state['values']['shift_value'];
	$user_direction = strtolower($form_state['values']['direction']);
	$user_phrase = strtolower($form_state['values']['phrase']);
	$user_letters = explode($user_phrase);
	$letters_array = ['a', 'b', 'c',
	'd',
	'e', 'f', 'g', 'h','i', 'j', 'k',
	'l',
		'm',
		'n',
		'o',
		'p',
		'q',
		'r',
		's',
		't',
		'u',
		'v',
		'w',
		'x',
		'y', 'z'];

	$punctuation_array = ['!', '.', ',', '?', ';', ':', '"',];
	$result = '';
	$shift_letters = array();
	$shift_phrase = array();

	foreach



// foreach($user_letters as $letter) {
// 	if ($user_direction == 'right') {
// 		$answer = $shift_value + $letters;
// 	} 
// }

// if ($user_direction === "right") {
// 	$answer = $user_phrase + $shift_value;
// } else {
// 	$answer = $user_phrase - $shift_value;
// }

	$answer = abs($shift_value + $user_phrase);

	$_SESSION ['encoded'] = $answer;
	$form_state['redirect'] = 'shift_cipher_success_page';
}

function shift_cipher_success() {
	$answer = $_SESSION['encoded'];
	return $answer;
}























